
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: datasets.metaedge.io
spec:
  # group name, use for REST API: /apis/<group>/<version>
  group: metaedge.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          description: Dataset describes the data that a dataset resource should have
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: DatasetSpec is a description of a dataset
              properties:
                credentialName:
                  type: string
                format:
                  type: string
                nodeName:
                  type: string
                url:
                  type: string
              required:
                - format
                - nodeName
                - url
              type: object
            status:
              description: DatasetStatus represents information about the status of
                a dataset including the time a dataset updated, and number of samples
                in a dataset
              properties:
                numberOfSamples:
                  type: integer
                updateTime:
                  format: date-time
                  type: string
              required:
                - numberOfSamples
              type: object
          required:
            - spec
          type: object
  scope: Namespaced
  names:
    kind: Dataset
    listKind: DatasetList
    plural: datasets
    singular: dataset
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
