// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "metaedge/pkg/client/clientset/versioned/typed/metaedge/v1alpha1"

	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeMetaedgeV1alpha1 struct {
	*testing.Fake
}

func (c *FakeMetaedgeV1alpha1) Datasets(namespace string) v1alpha1.DatasetInterface {
	return &FakeDatasets{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeMetaedgeV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
